INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DIR');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DD(AIA)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DD(FEA)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(SA)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(AP)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(AA)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(IR)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(FA)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DN(IPS)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('OSD');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('CSH');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DNACR');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('HND');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('PRO');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ADT');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ADM-II');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('SEC');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('HCU');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('DRV');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ACC');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('EXTAUDIT');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('REG');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ACD');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ADM');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('ADV');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('T_EXCH');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H11');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H8');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H6');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('EMD');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('CAD');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('CHEM');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('PHO');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('MMD');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('HSP ');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('VNV');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('JLV');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('EST');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('NCC');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H7');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H4');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('H2');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('Hill Side');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('AC Maintainance ');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('EST(Central and Lake side)');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('Press');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('SAC');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('SKIOSK');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('St. Counsellor');
INSERT INTO `cc_inventory`.`tbl_sections` (`name`) VALUES('Hindi Training');